const NOTION_TOKEN = process.env.NOTION_TOKEN;
const NOTION_DATABASE_ID = process.env.NOTION_DATABASE_ID;
const SLACK_SIGNING_SECRET = process.env.SLACK_SIGNING_SECRET;
const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN;
const SLACK_CHANNEL_ID = process.env.SLACK_CHANNEL_ID;
const DEFAULT_EXPORT = {
  NOTION_TOKEN,
  NOTION_DATABASE_ID,
  SLACK_SIGNING_SECRET,
  SLACK_BOT_TOKEN,
  SLACK_CHANNEL_ID,
};

export default DEFAULT_EXPORT;
