name: Cron

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install packages
        run: npm install

      - name: Start the app
        run: npm run start
